version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: menuly
      POSTGRES_USER: menuly_user
      POSTGRES_PASSWORD: menuly_pass
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./sistema_menuly:/app/sistema_menuly
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://menuly_user:menuly_pass@db:5432/menuly

volumes:
  postgres_data:
