# Generated by Django 5.2.4 on 2025-08-01 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurantes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RestauranteAdministrador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("gerente", "Gerente"),
                            ("funcionario", "Funcionário"),
                        ],
                        max_length=15,
                        verbose_name="Nível de Acesso",
                    ),
                ),
                (
                    "pode_editar_produtos",
                    models.BooleanField(
                        default=True, verbose_name="Pode Editar Produtos"
                    ),
                ),
                (
                    "pode_editar_configuracoes",
                    models.BooleanField(
                        default=False, verbose_name="Pode Editar Configurações"
                    ),
                ),
                (
                    "pode_ver_relatorios",
                    models.BooleanField(
                        default=True, verbose_name="Pode Ver Relatórios"
                    ),
                ),
                (
                    "pode_gerenciar_usuarios",
                    models.BooleanField(
                        default=False, verbose_name="Pode Gerenciar Usuários"
                    ),
                ),
                (
                    "pode_editar_pedidos",
                    models.BooleanField(
                        default=True, verbose_name="Pode Editar Pedidos"
                    ),
                ),
                (
                    "pode_configurar_impressoras",
                    models.BooleanField(
                        default=False, verbose_name="Pode Configurar Impressoras"
                    ),
                ),
                (
                    "pode_ver_financeiro",
                    models.BooleanField(
                        default=False, verbose_name="Pode Ver Financeiro"
                    ),
                ),
                (
                    "data_adicionado",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Adição"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "adicionado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="administradores_adicionados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Adicionado por",
                    ),
                ),
                (
                    "restaurante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurantes.restaurante",
                        verbose_name="Restaurante",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Administrador do Restaurante",
                "verbose_name_plural": "Administradores dos Restaurantes",
                "unique_together": {("restaurante", "usuario")},
            },
        ),
        migrations.AddField(
            model_name="restaurante",
            name="administradores",
            field=models.ManyToManyField(
                blank=True,
                related_name="restaurantes_gerenciados",
                through="restaurantes.RestauranteAdministrador",
                through_fields=("restaurante", "usuario"),
                to=settings.AUTH_USER_MODEL,
                verbose_name="Administradores",
            ),
        ),
    ]
